### ISSUE TITLE
UnityBuildV3: Invalid path mode for editors folder lookup specified

### ISSUE THREAD

**Issue by axtox** [Dinomite-Studios/unity-azure-pipelines-tasks#126]
All our builds failed because of yesterday's v3.1.0 release:
```Starting: Unity Android Build 
==============================================================================
Task         : Unity Build
Description  : Build a Unity project and get the exported output files.
Version      : 3.1.0
Author       : Dinomite Studios
Help         : Builds a Unity project to supported build target platforms. [More Information](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks)
==============================================================================
Invalid path mode for editors folder lookup specified.
##[error]Invalid path mode for editors folder lookup specified.
Finishing: Unity Android Build 
```

Our Unity Editor folder was specified manually in Unity Task properties. 
![image](https://user-images.githubusercontent.com/11292461/80120498-c7faa380-8593-11ea-84f6-0c84334442c6.png)

It was working for us until now.
We have a workaround for that issue - we had to specify Unity Editors environment variable on the agent and use it, but still maybe there will be a fix and we wont need to change all other definitions?

**Comment by FejZa** [comment]
Hi, thank you for reporting. I'll look into it. Sorry for the inconvenience.

**Comment by FejZa** [comment]
Hi @axtox, I just published v2.7.1 with a fix for your issue. Could you please verify and confirm? Thank you.

**Comment by FejZa** [comment]
v2.7.1 is the extension version. The build task with the fix is v3.1.1

**Comment by axtox** [comment]
This one is fixed, thank you so much!
However, we have a new issue #129 
Please, take a look.

**Comment by bdovaz** [comment]
Still a problem in our case:

https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks/issues/135#issuecomment-694093523
