### ISSUE TITLE
UWP build task fails

### ISSUE THREAD

**Issue by eusebiu** [Dinomite-Studios/unity-azure-pipelines-tasks#91]
I am trying to build for UWP but the task fails and the log contains no errors.

The Unity build task has the Build target set to UWP and in Advanced section the Command line arguments are 
-quit -nographics -executeMethod BuildUWP.PerformBuild -logFile $(logpath.logFilePath)

`[command]"C:\Program Files\Unity\Hub\Editor\2019.1.12f1\Editor\Unity.exe" -batchmode -buildTarget WindowsStoreApps -projectPath d:\a\1\s\App -quit -nographics -executeMethod BuildUWP.PerformBuild -logFile d:\a\1\s\UnityActivationLog.log

Checking whether Unity process is still running...

Unity process has finished. Checking for build output in d:\a\1\s\App\Build\WindowsStoreApps
##[debug]task result: Failed
##[error]The Unity build task finished without results. Check editor logs for details.

public class BuildUWP : MonoBehaviour
{
#if UNITY_EDITOR
	[MenuItem("Build/Virtu/UWP")]
	public static void PerformBuild()
	{
		BuildPlayerOptions buildPlayerOptions = new BuildPlayerOptions();

		buildPlayerOptions.scenes = new[] {
			"Assets/Scenes/Main.unity",
		};

		var outputFile = "./BuildUWP/";

		buildPlayerOptions.locationPathName = outputFile;
		buildPlayerOptions.target = BuildTarget.WSAPlayer;
		buildPlayerOptions.targetGroup = BuildTargetGroup.WSA;

		BuildPipeline.BuildPlayer(buildPlayerOptions);
	}
#endif
}`

If I run the same command on a local machine, the build is succcessful.
Any idea why?

**Comment by FejZa** [comment]
Hi, the current build task does not work like that. You cannot specify your own -executeMethod since the task will still put it's own one in there.

I just published a preview of Version 3 of the task. Please update the extension from the Visual Studio Marketplace and update your pipeline to use Unity Build V3 (Preview). Then for `Build Script Type` set it to "Existing". Then for `Build Script Execute Method` set "BuildUWP.PerformBuild".

I am looking forward to your feedback since I am in need of some people testing V3 for their own scenarios.

**Comment by eusebiu** [comment]
The Bug with getting the version is back
##[error]Error: Not found Unity Editor Directory: C:\Program Files\Unity\Hub\Editor\2019.1.12f1
m_EditorVersionWithRevision\Editor

The Unity Get Project Version:
##[debug]Evaluating condition for step: 'Unity Get Project Version'
##[debug]Evaluating: succeeded()
##[debug]Evaluating succeeded:
##[debug]=> True
##[debug]Result: True
##[section]Starting: Unity Get Project Version
==============================================================================
Task         : Unity Get Project Version
Description  : Gets the project version of a Unity project.
Version      : 1.0.2
Author       : Dinomite Studios
Help         : Gets the project version of a Unity project. [More Information](https://github.com/Dinomite-Studios/unity-azure-pipelines-tasks)
==============================================================================
##[debug]agent.TempDirectory=D:\a\_temp
##[debug]loading inputs and endpoints
##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
##[debug]loading INPUT_UNITYPROJECTPATH
##[debug]loading SECRET_PASSWORD
##[debug]loading SECRET_SERIAL
##[debug]loaded 6
##[debug]Agent.ProxyUrl=undefined
##[debug]Agent.CAInfo=undefined
##[debug]Agent.ClientCert=undefined
##[debug]Agent.SkipCertValidation=undefined
##[debug]check path : D:\a\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.2\task.json
##[debug]adding resource file: D:\a\_tasks\UnityGetProjectVersionTask_38ec98bf-601a-4390-9f2e-23d43dd6dbba\1.0.2\task.json
##[debug]system.culture=en-US
##[debug]unityProjectPath=D:\a\1\s\App
##[debug]set projectVersion=2019.1.12f1
m_EditorVersionWithRevision
##[debug]Processed: ##vso[task.setvariable variable=projectVersion;issecret=false;]2019.1.12f1%0D%0Am_EditorVersionWithRevision
##[debug]task result: Succeeded
##[debug]Processed: ##vso[task.complete result=Succeeded;]Found project version: 2019.1.12f1%0D%0Am_EditorVersionWithRevision
##[section]Finishing: Unity Get Project Version

**Comment by eusebiu** [comment]
Any news on this?

**Comment by FejZa** [comment]
Hi @eusebiu , I just released v2.5.2 of the extensions to the marketplace. Could you please make sure you updated to that version and run your pipeline again? Please make sure that the `debug` system variable is set to `true`, so we get better output.

If you have the latest versions, you should be seeing these versions used:
Unity Get Project Version: 1.0.4
Unity Activate License: 1.0.4

Thanks for the help!

**Comment by eusebiu** [comment]
I now get:
[UnityConnectServicesConfig] config is NOT valid, switching to default
Created GICache directory at C:/Users/VssAdministrator/AppData/LocalLow/Unity/Caches/GiCache. Took: 0.059s, timestamps: [2998.662 - 2998.722]
[0814/210627:ERROR:gpu_info_collector_win.cc(103)] Can't retrieve a valid WinSAT assessment.

**Comment by christopheph** [comment]
Hi, @FejZa Any news about this issue ? We still have the same error described by @eusebiu .

Thank you in advance for your help.

Best Regards,

**Comment by FejZa** [comment]
@christopheph I want to make sure you are on the latest version, could you check that? The issue should be resolved with the last update. Or are you talking about the the other issue regarding the WinSAT assessment? In that case could you try and add the -nographics flag to the build arguments?

**Comment by eusebiu** [comment]
The -nographics is added to the custom arguments. 

[command]"C:\Program Files\Unity\Hub\Editor\2019.2.3f1\Editor\Unity.exe" -batchmode -buildTarget WindowsStoreApps -projectPath d:\a\1\s\AppName - quit -nographics -executeMethod BuildUWP.PerformBuild

**Comment by christopheph** [comment]
@FejZa would it be possible to organize a conf call next week via skype so me and @eusebiu can show you what we do ? Thank you in advance

**Comment by FejZa** [comment]
Hi everyone, better late than never I just published v2.7 of the extension. All of the tasks will now stream logs to DevOps. So you can easily monitor what's going on. Also V3 of the build task gives you options to use your own build scripts. Also there is now a `Unity CMD` task for full control.
